### PR TITLE
Kubo Compat + Dag Endpoints

### PR DESCRIPTION
**Pull request by IvantheTricourne**
API still works, except most endpoints are now `POST`s instead of `GET`s.

Also adds `dag` endpoints for `get` and `put`.

### CODE REVIEW

**Comment by IvantheTricourne** [comment]
Not sure if this is something I did wrong, or if it's just the nature of the `put`ing:

```
  1) V0.DagAPI, the v0 Dag API, can put dags
       expected: CIDResponse {cid = "bafyreif5tiacshzdgycildbxumfz7bp4vbtljdiybhnrf2i2xxumixrmiq"}
        but got: CIDResponse {cid = "zdpuAyBZjeKaoAZkKGyNH82CP1QUhVvLHATdFTZcbpv84Tgwm"}
```

Seems like the hash result from putting is different.

**Comment by mattearl** [comment]
looks like the base is different

expected
```
base32 - cidv1 - dag-cbor - (sha2-256 : 256 : BD9A00291F233604858C37A30B9F85FCA866B48D1809DB12E91ABDE8C45E2C44)
```

actual
```
base58btc - cidv1 - dag-cbor - (sha2-256 : 256 : BD9A00291F233604858C37A30B9F85FCA866B48D1809DB12E91ABDE8C45E2C44)
```

**Comment by mattearl** [comment]
this is a handy site for CID breakdown:  https://cid.ipfs.tech/

**Comment by iostat** [comment]
CID type should be a Multihash instead of a String, and then you can actually compare the expected hashes regardless of base:

https://github.com/multiformats/haskell-multihash/tree/master/src/Data/Multihash

in fact i'd say you should be using the types above for hash choice as well, and test that it works...

**Review by iostat — CHANGES_REQUESTED** [review]
^

**Comment by iostat** [comment]
Also, can we check that this still works with newer stack LTS

**Comment by IvantheTricourne** [comment]
> Also, can we check that this still works with newer stack LTS

Can confirm. It works both importing in `hostel-chronos` without changing the `lts` value in `stack.yaml` and also with changing to `lts-18.28` (with some small, minor changes). Either is a viable option.

**Comment by iostat** [comment]
from travis:
```
[ 3 of 10] Compiling Servant.MultipartFormData

/home/travis/build/f-o-a-m/ipfs-api/src/Servant/MultipartFormData.hs:30:10: warning: [-Wmissing-methods]

    • No explicit implementation for

        ‘hoistClientMonad’

    • In the instance declaration for

        ‘HasClient m (MultipartFormDataReqBody b :> Post (ct : cts) a)’

   |

30 | instance (MonadIO m, RunClient m, MimeUnrender ct a, ToMultipartFormData b) =>

   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
a) this needs a -Werror
b) seems like it should be implemented, since we're using this primarily as a client...

**Review by iostat — APPROVED** [review]

**Pull request merged**
